### ISSUE TITLE
The config in the readme is incorrect

### ISSUE THREAD

**Issue by believer** [JobtechSwe/mydata#6]
- Missing two commas (end of `description` row and end of `clientKeys` object).
- `jwksUrl` and `eventsUrl` should be `jwksPath` and `eventsPath` respectively
- `operatorUrl` should be `operator`

**Updated example:**

```js
const config = {
  displayName: 'The name of your service',
  description: 'A nice description of your fantastic service',
  clientId: 'https://mycv.work', // Application domain with protocol
  operator: 'https://smoothoperator.work', // URL of Operator
  clientKeys: {
    publicKey: '',
    privateKey: ''
  },
  jwksPath: '/jwks',     // endpoint for keys in jwks format
  eventsPath: '/events'  // endpoint for events - webhook style
}
```

**Comment by einarpersson** [comment]
Thanks! Colons are added in https://github.com/JobtechSwe/mydata/commit/abad208c34c48e76265cf6b36c90a9053c233af0

Naming of config properties is under consideration and discussion and some properties might disappear all together (jwksUrl?).

**Comment by einarpersson** [comment]
Ah! I just realized that you were right about the other things as well. I thought we hadn't changed to jwksPath but we seem to have done so in the external api (but not internally)

I'll update the Readme and verify that it's working

**Comment by believer** [comment]
Sweet!

**Comment by einarpersson** [comment]
Fixed in https://github.com/JobtechSwe/mydata/commit/a28c9ae5e05acbba67cfc24c3fff9f5b4be4594f
